project_identifier_env: CROWDIN_PROJECT
api_key_env: CROWDIN_API_KEY
base_path: /kolibri/locale/en
preserve_hierachy: true

files:
  - source: 'LC_FRONTEND_MESSAGES/*.json'
    translation: '/kolibri/locale/%locale_with_underscore%/LC_FRONTEND_MESSAGES/%original_file_name%'

  - source: 'LC_MESSAGES/*.po'
    translation: '/kolibri/locale/%locale_with_underscore%/LC_MESSAGES/%original_file_name%'
