steps:
  - label: Build the docker environment
    command: .buildkite/build_dockerenv.sh

  - wait

  - label: Build the python packages
    command: mkdir -p dist && .buildkite/build_whl.sh

  - wait

  - label: Build the pex file
    command: mkdir -p dist && .buildkite/build_pex.sh
